config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/create'
  # get 'sessions/destroy'

  # get 'home/show'

  # devise_for :users
  resources :questions do
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
  end

  devise_for :users
  resources :users, :has_one => :profile
  resources :profiles

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'

  #:controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: "home#index"
end

# Twealr::Application.routes.draw do
#   get 'auth/:provider/callback', to: 'sessions#create'
#   get 'auth/failure', to: redirect('/')

#   get 'signout', to: 'sessions#destroy', as: 'signout'

#   resources :sessions, only: [:create, :destroy]
#   resource :home, only: [:show]

#   root to: "home#index"
# end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :comments
  validates :title, :presence => {:message => 'Title cannot be blank, Question not posted'},
                    length: {minimum: 5, maximum: 100}
  validates :text, :presence => {:message => 'Your question must contain some content, Question not posted'},
                    length: {minimum: 25, maximum: 500}
end

app/controllers/questions_controller.rb
class QuestionsController < SecuredController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build
  end

  def index
    @questions = Question.all
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
  @question = Question.find(params[:id])

  if @question.update(question_params)
    redirect_to @question
  else
    render 'edit'
  end
end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
end


  private
  def question_params
    params.require(:question).permit(:title, :text)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
<% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited
      this question from being saved:</h2>
    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Save', class: 'btn btn-default' %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>
<%= link_to 'New question', new_question_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.text %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
      <td><%= link_to 'Destroy', question_path(question),
                    method: :delete, data: { confirm: 'Are you sure?' }
      %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<h2>Answers</h2>
<% @question.answers.each do |answer| %>
<% unless answer.new_record? %>
  <p>
    <strong>Text:</strong>
    <%= answer.text %>
  </p>
  <% end %>
<% end %>

<h2>Add a answer:</h2>
<%= form_for([@question, @answer]) do |f| %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit Question', edit_question_path(@question) %> |
<%= link_to 'Back to Questions', questions_path %>