config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/create'
  # get 'sessions/destroy'

  # get 'home/show'

  # devise_for :users
  resources :questions do
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
  end

  devise_for :users
  resources :users, :has_one => :profile
  resources :profiles

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'

  #:controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: "home#index"
end

# Twealr::Application.routes.draw do
#   get 'auth/:provider/callback', to: 'sessions#create'
#   get 'auth/failure', to: redirect('/')

#   get 'signout', to: 'sessions#destroy', as: 'signout'

#   resources :sessions, only: [:create, :destroy]
#   resource :home, only: [:show]

#   root to: "home#index"
# end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true,
                    length: { minimum: 5, maximum: 140 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :get_profile, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.find(params[:user_id])
    @profile = @user.profile.build
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.profile.build(params[:profile])
    if @profile.save
      flash[:success] = "Your profile has been saved successfully."
    redirect_to new_user_proile_path(:user_id => @user)
    else
      flash[:notice] = 'Error. Something went wrong.'
      render :new
    end
  end

  def edit
  @profile = user.profile
  end

  def update
      if @profile.update(profile_params)
        redirect_to @profile, notice: 'The profile was successfully updated.'
        render :show, status: :ok, location: @profile
      else
       render :edit
      end
  end


  def destroy
    @profile.destroy
      redirect_to profile_url, notice: 'The profile was successfully deleted.'
  end

  def get_profile
    @user = User.find(params[:user_id])
    @profile = @user.profile.build
 end

  private

  def profile_params
    params.require(:profile).permit([:name, :photo])
  end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_profileform.html.erb
%= form_for @profile do |p| %>

   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </p>

 <p>
   <%= f.submit 'Save', class: 'btn btn-default' %>
 </p>
<% end %>

app/views/profiles/create.html.erb
<h1>New Profile</h1>
<p>Update your profile today! And let others see who you are! </p>

<%= form_for :profile do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name%>
  <p>

  <p>
    <%= f.submit %>
  <p>
  <br><br><br>

  <% end %>

app/views/profiles/edit.html.erb
<h1>Edit Your Profile</h1>

<%= link_to "Profile", edit_profile_path(user.profile) %>

<%= link_to 'Back', questions_path %>

app/views/profiles/index.html.erb
<h1>All Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= 'Profiles' %>

  <tbody>
    <% @profiles.each do |profile| %>
     <td>
            <%= profile.name %>
          </td>
      <tr>
        <td><%= link_to profile.name, profile_path(profile) %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<p>Create your profile today! And let others see you!</p>

<%= form_for :profile, url: {action: create} do |f| %>
  <p>
    <%= f.label :Name%><br>
    <%= f.text_field :name%>
  <p>

  <p>
    <%= f.submit %>
  <p>
  <br><br><br>

  <% end %>

app/views/profiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @profile.name %>

</p>