config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/create'
  # get 'sessions/destroy'

  # get 'home/show'

  # devise_for :users
  resources :questions do
    resources :answers
    resources :comments
  end

  resources :answers do
    resources :comments
  end

  devise_for :users
  resources :users, :has_one => :profile
  resources :profiles

  get 'pages/about' => 'high_voltage/pages#show', id: 'about'

  #:controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: "home#index"
end

# Twealr::Application.routes.draw do
#   get 'auth/:provider/callback', to: 'sessions#create'
#   get 'auth/failure', to: redirect('/')

#   get 'signout', to: 'sessions#destroy', as: 'signout'

#   resources :sessions, only: [:create, :destroy]
#   resource :home, only: [:show]

#   root to: "home#index"
# end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :comments
  validates :text, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < SecuredController
  def new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)

    if @answer.save
      redirect_to question_path(@question)
    else
      render 'new'
    end
  end

    def show
  @question = Question.find(params[:id])
  @answer = @question.answers.build
  end

  def index
  @answers = Answer.all
  end

  private
    def answer_params
      params.require(:answer).permit(:text)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <!--<th>Title</th>-->
    <th>Text</th>
  </tr>

  <% @answers.each do |answer| %>
    <tr>
      <td><%= answer.text %></td>
    <td><%= link_to 'Show', question_path(:question) %></td>
      <td><%= link_to 'Edit', edit_question_path(:question) %></td>
      <td><%= link_to 'Destroy', question_path(:question),
                    method: :delete, data: { confirm: 'Are you sure?' }
      %></td>
    </tr>
  <% end %>
</table>

app/views/answers/new.html.erb
<h1>New Answer</h1>
<%= form_for :article, url: articles_path do |f| %>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @answer.text %>
</p>

<h2>Comments</h2>
<% @answer.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@answer, @answer.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit Answer', edit_answer_path(@answer) %> |
<%= link_to 'Back to Answers', answers_path %>